project:
  name: Government Complaint Department Classification
  version: 1.0.0
  author: Kashak Joshi

logging:
  log_dir: logs
  log_level: INFO

artifacts:
  root_dir: artifacts

random_seed: 42

dataset:
  file_extension: ".csv"

  required_columns:
    - post_title
    - post_description
    - department_name

  optional_columns:
    - post_id
    - department_id
    - label

data_cleaning:
  output_file: data/interim/cleaned_dataset.csv

  remove_duplicates: true
  remove_null_complaints: true
  remove_null_departments: true

  complaint_column: post_description
  sender_column: post_title
  department_column: department_name

feature_engineering:
  output_file: artifacts/features/features.pt
  label_encoder_path: artifacts/features/label_encoder.pkl
  complaint_column: complaint
  department_column: department

text_input:
  max_text_length: 5000
  min_text_length: 3
  accepted_input_type: "text"
  remove_leading_trailing_spaces: true
  convert_to_string: true

ocr:
  supported_formats:
    - jpg
    - jpeg
    - png

  languages:
    - en
    - hi

  use_gpu: false

  min_image_size: 50
  max_image_size: 10000

hindi_nlp:

  normalize_spaces: true

  normalize_tabs: true

  normalize_newlines: true
  remove_special_characters: true
  evaluate_numbers: true
  analyze_stopwords: true
  evaluate_stemming: true
  evaluate_lemmatization: true

  output_file: data/processed/hindi_preprocessed_dataset.csv